"""Adjusted model to resolve join issue

Revision ID: 20fcb35727eb
Revises: 8f2d17ee114b
Create Date: 2023-09-10 23:10:20.596207

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "20fcb35727eb"
down_revision: Union[str, None] = "8f2d17ee114b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
