"""Added expense name to Expense model

Revision ID: 6f087cf98b62
Revises: 3dd4aaaab3ec
Create Date: 2023-10-31 00:32:13.477450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f087cf98b62'
down_revision: Union[str, None] = '3dd4aaaab3ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('name', sa.String(length=255), nullable=False, server_default='some expense'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'name')
    # ### end Alembic commands ###
