"""Adjusted model to resolve join issue #2

Revision ID: 9300dd6def88
Revises: 20fcb35727eb
Create Date: 2023-09-10 23:16:24.574520

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "9300dd6def88"
down_revision: Union[str, None] = "20fcb35727eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
